# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 10:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_remove_comment_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_counter',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
