# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170302_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
