# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170302_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like',
            new_name='like_counter',
        ),
    ]
