# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170309_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='new_like',
        ),
    ]
