# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_like_new_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
